name: macos-cli

on: [push, pull_request]

jobs:
  build-macos:
    env:
      CMAKE_OSX_DEPLOYMENT_TARGET: 10.14
      OSX_MIN_VERSION: 10.14
      USE_SINGLE_BUILDDIR: 1
    runs-on: macOS-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12.0'
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: install dependencies
      run: brew install zmq libpgm miniupnpc ldns expat libunwind-headers protobuf unbound
    - name: build boost
      run: |
        wget https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.gz
        tar -xzf boost_1_71_0.tar.gz
        cd boost_1_71_0
        ./bootstrap.sh 
        ./b2
        ./b2 install
    - name: build
      run: |
        make release-static-mac-x86_64 -j${nproc}
        chmod +x build/release/bin/*
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Haven-MacOS
        path: build/release/bin/
